# Generated by Django 2.2.6 on 2019-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
