# Generated by Django 2.2.6 on 2019-11-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='id',
        ),
        migrations.AddField(
            model_name='models',
            name='model_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
