# Generated by Django 2.2.6 on 2019-11-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20191108_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
    ]
