# Generated by Django 2.2.6 on 2019-11-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_delete_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=60)),
                ('carcass', models.CharField(max_length=100)),
                ('years_of_productions', models.CharField(max_length=10)),
                ('engines', models.CharField(max_length=50)),
                ('transmissions', models.CharField(max_length=50)),
                ('drive_units', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
    ]
