# Generated by Django 2.2.6 on 2019-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20191109_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
