# Generated by Django 2.2.6 on 2019-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_order', models.DateField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deliveries',
                'managed': False,
            },
        ),
    ]
