# Generated by Django 2.2.6 on 2019-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycars',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('car_body', models.CharField(max_length=20)),
                ('car_year', models.CharField(max_length=4)),
                ('engine', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('drive_unit', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=25)),
                ('mileage', models.BigIntegerField(blank=True, null=True)),
                ('identification_number', models.CharField(max_length=20)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('photos', models.ImageField(upload_to='')),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('options', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mycars',
                'managed': False,
            },
        ),
    ]
