CREATE TABLE "USERS" (
	"ID" INT NOT NULL,
	"LOGIN" VARCHAR2(20) UNIQUE NOT NULL,
	"PASSWORD" VARCHAR2(30) NOT NULL,
	"USER_TYPE" VARCHAR2(10),
	constraint USERS_PK PRIMARY KEY ("ID"));

CREATE sequence "USERS_ID_SEQ";

DROP trigger "BI_USERS_ID";
CREATE trigger "BI_USERS_ID"
  before insert on "USERS"
  for each row
begin
  select "USERS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "CUSTOMERS" (
	"ID" INT NOT NULL,
	"LOGIN_ID" INT UNIQUE NOT NULL,
	"FIO" VARCHAR2(200),
	"PHONE" VARCHAR2(20),
	"ADDRESS" VARCHAR2(200),
	"EMAIL" VARCHAR2(100),
	"PERSON" VARCHAR2(15),
	constraint CUSTOMERS_PK PRIMARY KEY ("ID"));

CREATE sequence "CUSTOMERS_ID_SEQ";

DROP trigger "BI_CUSTOMERS_ID";
CREATE trigger "BI_CUSTOMERS_ID"
  before insert on "CUSTOMERS"
  for each row
begin
  select "CUSTOMERS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "CARS" (
	"ID" INT NOT NULL,
	"MARK" VARCHAR2(30) NOT NULL,
	"MODEL" VARCHAR2(60) NOT NULL,
	"CARCASS" VARCHAR2(100) NOT NULL,
	"YEARS_OF_PRODUCTIONS" VARCHAR2(10) NOT NULL,
	"ENGINES" VARCHAR2(50) NOT NULL,
	"TRANSMISSIONS" VARCHAR2(50) NOT NULL,
	"DRIVE_UNITS" VARCHAR2(20) NOT NULL,
	constraint CARS_PK PRIMARY KEY ("ID"));

CREATE sequence "CARS_ID_SEQ";

DROP trigger "BI_CARS_ID";
CREATE trigger "BI_CARS_ID"
  before insert on "CARS"
  for each row
begin
  select "CARS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "REQUESTS" (
	"ID" INT NOT NULL,
	"CAR_ID" INT NOT NULL,
	"DATE_REQUEST" DATE NOT NULL,
	"CUSTOMER_ID" INT NOT NULL,
	"REQUEST_STATUS" VARCHAR2(20) NOT NULL,
	"DELIVERY" CHAR(1) CHECK ("DELIVERY" IN ('N','Y')) NOT NULL,
	"DELIVERY_ADDRESS" VARCHAR2(200),
	"COST" FLOAT NOT NULL,
	constraint REQUESTS_PK PRIMARY KEY ("ID"));

CREATE sequence "REQUESTS_ID_SEQ";

DROP trigger "BI_REQUESTS_ID";
CREATE trigger "BI_REQUESTS_ID"
  before insert on "REQUESTS"
  for each row
begin
  select "REQUESTS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "ORDERS" (
	"ID" INT NOT NULL,
	"REQUEST_ID" INT NOT NULL,
	"ORDER_STATUS" VARCHAR2(20) NOT NULL,
	"START_DATE" DATE,
	"END_DATE" DATE,
	constraint ORDERS_PK PRIMARY KEY ("ID"));

CREATE sequence "ORDERS_ID_SEQ";

DROP trigger "BI_ORDERS_ID";
CREATE trigger "BI_ORDERS_ID"
  before insert on "ORDERS"
  for each row
begin
  select "ORDERS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "MYCARS" (
	"ID" INT NOT NULL,
	"CAR_ID" INT NOT NULL,
	"CAR_BODY" VARCHAR2(20) NOT NULL,
	"CAR_YEAR" VARCHAR2(4) NOT NULL,
	"ENGINE" VARCHAR2(20) NOT NULL,
	"TRANSMISSION" VARCHAR2(20) NOT NULL,
	"DRIVE_UNIT" VARCHAR2(5) NOT NULL,
	"COLOR" VARCHAR2(25) NOT NULL,
	"MILEAGE" INT,
	"IDENTIFICATION_NUMBER" VARCHAR2(20) NOT NULL,
	"COST" FLOAT,
	"PHOTOS" VARCHAR2(255),
	"DATE_OF_DELIVERY" DATE,
	"DESCRIPTION" VARCHAR2(2000),
	"OPTIONS" VARCHAR2(200),
	constraint MYCARS_PK PRIMARY KEY ("ID"));

CREATE sequence "MYCARS_ID_SEQ";

DROP trigger "BI_MYCARS_ID";
CREATE trigger "BI_MYCARS_ID"
  before insert on "MYCARS"
  for each row
begin
  select "MYCARS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "DELIVERIES" (
	"ID" INT NOT NULL,
	"SHIPPER_ID" INT NOT NULL,
	"CAR_ID" INT NOT NULL,
	"DATE_ORDER" DATE,
	"COST" FLOAT,
	constraint DELIVERIES_PK PRIMARY KEY ("ID"));

CREATE sequence "DELIVERIES_ID_SEQ";

DROP trigger "BI_DELIVERIES_ID";
CREATE trigger "BI_DELIVERIES_ID"
  before insert on "DELIVERIES"
  for each row
begin
  select "DELIVERIES_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "SUPPLIERS" (
	"ID" INT NOT NULL,
	"NAME" VARCHAR2(50) NOT NULL,
	"ADDRESS" VARCHAR2(200),
	"PHONE" VARCHAR2(20),
	"EMAIL" VARCHAR2(100),
	constraint SUPPLIERS_PK PRIMARY KEY ("ID"));

CREATE sequence "SUPPLIERS_ID_SEQ";

DROP trigger "BI_SUPPLIERS_ID";
CREATE trigger "BI_SUPPLIERS_ID"
  before insert on "SUPPLIERS"
  for each row
begin
  select "SUPPLIERS_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/

ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_fk0" FOREIGN KEY ("LOGIN_ID") REFERENCES "USERS"("ID");


ALTER TABLE "REQUESTS" ADD CONSTRAINT "REQUESTS_fk0" FOREIGN KEY ("CAR_ID") REFERENCES "MYCARS"("ID");
ALTER TABLE "REQUESTS" ADD CONSTRAINT "REQUESTS_fk1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMERS"("ID");

ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_fk0" FOREIGN KEY ("REQUEST_ID") REFERENCES "REQUESTS"("ID");

ALTER TABLE "MYCARS" ADD CONSTRAINT "MYCARS_fk0" FOREIGN KEY ("CAR_ID") REFERENCES "DELIVERIES"("ID");

ALTER TABLE "DELIVERIES" ADD CONSTRAINT "DELIVERIES_fk0" FOREIGN KEY ("SHIPPER_ID") REFERENCES "SUPPLIERS"("ID");
ALTER TABLE "DELIVERIES" ADD CONSTRAINT "DELIVERIES_fk1" FOREIGN KEY ("CAR_ID") REFERENCES "CARS"("ID");


